# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(428, 316)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.list_widget = QtWidgets.QListWidget(self.centralwidget)
        self.list_widget.setGeometry(QtCore.QRect(60, 30, 311, 141))
        self.list_widget.setObjectName("list_widget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 0, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.add_button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.add_task())
        self.add_button.setGeometry(QtCore.QRect(60, 210, 81, 31))
        self.add_button.setObjectName("add_button")
        self.delete_button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.delete_task())
        self.delete_button.setGeometry(QtCore.QRect(170, 210, 71, 31))
        self.delete_button.setObjectName("delete_button")
        self.clear_button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.clear_list())
        self.clear_button.setGeometry(QtCore.QRect(270, 210, 71, 31))
        self.clear_button.setObjectName("clear_button")
        self.input_text = QtWidgets.QLineEdit(self.centralwidget)
        self.input_text.setGeometry(QtCore.QRect(110, 180, 191, 20))
        self.input_text.setObjectName("input_text")
        self.error_output = QtWidgets.QLabel(self.centralwidget)
        self.error_output.setGeometry(QtCore.QRect(120, 250, 171, 20))
        self.error_output.setText("")
        self.error_output.setObjectName("error_output")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 428, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "To Do List"))
        self.add_button.setText(_translate("MainWindow", "Add Task"))
        self.delete_button.setText(_translate("MainWindow", "Delete Task"))
        self.clear_button.setText(_translate("MainWindow", "Clear List"))

    #Add task to list
    def add_task(self):
        self.error_output.setText('')
        task = self.input_text.text().lower()
        if task == '':
            self.error_output.setText('Please enter a task!')
        else:
            self.list_widget.addItem(task)
        self.input_text.setText('')

    #Deletes selected task from list
    def delete_task(self):
        self.error_output.setText('')
        if self.list_widget.count() == 0:
            self.error_output.setText('List is empty!')
        else:
            clicked = self.list_widget.currentRow()
            self.list_widget.takeItem(clicked)


    #Clears entire list
    def clear_list(self):
        if self.list_widget.count() == 0:
            self.error_output.setText('List is already empty!')
        else:
            self.list_widget.clear()
            self.error_output.setText('')

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
